# Generated by Django 3.1b1 on 2020-08-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
