# Generated by Django 3.1b1 on 2020-09-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtf', '0003_testresult_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testreference',
            name='test_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='status',
            field=models.CharField(choices=[('skip', 'skip'), ('successful', 'successful'), ('unstable', 'unstable'), ('unknown', 'unknown'), ('failed', 'failed'), ('broken', 'broken')], default='unknown', max_length=20),
        ),
    ]
