# Generated by Django 3.1b1 on 2020-10-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtf', '0005_submission_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
