# Generated by Django 3.1b1 on 2020-12-03 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtf', '0007_addprojectslug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubmissionProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('required', models.BooleanField(default=False)),
                ('display', models.BooleanField(default=True)),
                ('display_replace', models.CharField(blank=True, max_length=100)),
                ('display_as_link', models.BooleanField(default=False)),
                ('influence_reference', models.BooleanField(default=False)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dtf.project')),
            ],
        ),
        migrations.AddConstraint(
            model_name='projectsubmissionproperty',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_submission_property'),
        ),
    ]
