# Generated by Django 3.1b1 on 2020-12-04 16:55

import collections
from django.db import migrations, models
import django.db.models.deletion
import dtf.models


class Migration(migrations.Migration):

    dependencies = [
        ('dtf', '0008_auto_20201203_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testreference',
            name='project',
        ),
        migrations.AlterField(
            model_name='projectsubmissionproperty',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='dtf.project'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='dtf.project'),
        ),
        migrations.CreateModel(
            name='ReferenceSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_values', models.JSONField(decoder=dtf.models.ReferenceSet.OrderedDictJSONDecoder, default=collections.OrderedDict, unique=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_sets', to='dtf.project')),
            ],
        ),
        migrations.AddField(
            model_name='testreference',
            name='reference_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_references', to='dtf.referenceset'),
        ),
    ]
