# Generated by Django 3.1b1 on 2020-12-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtf', '0009_add_reference_sets'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='testreference',
            constraint=models.UniqueConstraint(fields=('reference_set', 'test_name'), name='unique_test_reference_property'),
        ),
    ]
