# Generated by Django 3.1b1 on 2020-12-09 08:36

import collections
from django.db import migrations, models
import dtf.models


class Migration(migrations.Migration):

    dependencies = [
        ('dtf', '0010_add_reference_sets_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceset',
            name='property_values',
            field=models.JSONField(decoder=dtf.models.ReferenceSet.OrderedDictJSONDecoder, default=collections.OrderedDict),
        ),
        migrations.AddConstraint(
            model_name='referenceset',
            constraint=models.UniqueConstraint(fields=('project', 'property_values'), name='unique_project_property_values'),
        ),
    ]
