# Generated by Django 3.1b1 on 2020-12-10 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtf', '0011_add_reference_sets_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsubmissionproperty',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='dtf.project'),
        ),
        migrations.AlterField(
            model_name='referenceset',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_sets', to='dtf.project'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='dtf.project'),
        ),
        migrations.AlterField(
            model_name='testreference',
            name='reference_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_references', to='dtf.referenceset'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='submission',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='dtf.submission'),
        ),
    ]
