# Generated by Django 3.1b1 on 2020-12-11 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtf', '0013_created_and_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('secret_token', models.CharField(max_length=200)),
                ('on_submission', models.BooleanField(default=True)),
                ('on_test_result', models.BooleanField(default=True)),
                ('on_reference_set', models.BooleanField(default=True)),
                ('on_test_reference', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='dtf.project')),
            ],
        ),
    ]
