# Generated by Django 3.1.7 on 2021-03-07 13:36

from django.db import migrations, models
import django.db.models.deletion

def delete_unrelated_objects(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    apps.get_model('dtf', 'ProjectSubmissionProperty').objects.using(db_alias).filter(project=None).delete()
    apps.get_model('dtf', 'ReferenceSet').objects.using(db_alias).filter(project=None).delete()
    apps.get_model('dtf', 'Submission').objects.using(db_alias).filter(project=None).delete()
    apps.get_model('dtf', 'TestReference').objects.using(db_alias).filter(reference_set=None).delete()
    apps.get_model('dtf', 'TestResult').objects.using(db_alias).filter(submission=None).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dtf', '0015_add_webhook_logs'),
    ]

    operations = [
        migrations.RunPython(delete_unrelated_objects, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='projectsubmissionproperty',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='dtf.project'),
        ),
        migrations.AlterField(
            model_name='referenceset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_sets', to='dtf.project'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='dtf.project'),
        ),
        migrations.AlterField(
            model_name='testreference',
            name='reference_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_references', to='dtf.referenceset'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='dtf.submission'),
        ),
    ]
