# Generated by Django 3.1b1 on 2020-12-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtf', '0015_add_webhook_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooklogentry',
            name='trigger',
            field=models.CharField(choices=[('Submission', 'Submission'), ('TestResult', 'TestResult'), ('ReferenceSet', 'ReferenceSet'), ('TestReference', 'TestReference')], default='Submission', max_length=20),
            preserve_default=False,
        ),
    ]
