# Generated by Django 3.1.7 on 2021-03-12 12:22

from django.db import migrations, models
import dtf.validators


class Migration(migrations.Migration):

    dependencies = [
        ('dtf', '0019_introduce_ndarray'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testreference',
            name='references',
            field=models.JSONField(default=dict, validators=[dtf.validators.JSONSchemaValidator(schema={'additionalProperties': {'additionalProperties': False, 'properties': {'source': {'type': 'integer'}, 'value': {'$ref': '#/definitions/value'}}, 'required': ['value'], 'type': 'object'}, 'definitions': {'value': {'$id': '#value', 'additionalProperties': False, 'allOf': [{'if': {'properties': {'type': {'const': 'integer'}}}, 'then': {'properties': {'data': {'type': 'integer'}}}}, {'if': {'properties': {'type': {'const': 'float'}}}, 'then': {'properties': {'data': {'type': 'number'}}}}, {'if': {'properties': {'type': {'const': 'string'}}}, 'then': {'properties': {'data': {'type': 'string'}}}}, {'if': {'properties': {'type': {'const': 'duration'}}}, 'then': {'properties': {'data': {'pattern': '^(?P<sign>[-+]?)P(?:(?P<days>\\d+(\\.\\d+)?)D)?(?:T(?:(?P<hours>\\d+(\\.\\d+)?)H)?(?:(?P<minutes>\\d+(\\.\\d+)?)M)?(?:(?P<seconds>\\d+(\\.\\d+)?)S)?)?$', 'type': 'string'}}}}, {'if': {'properties': {'type': {'const': 'ndarray'}}}, 'then': {'properties': {'data': {'additionalProperties': False, 'properties': {'entries': {'items': {'$ref': '#/definitions/value'}, 'type': 'array'}, 'shape': {'items': {'type': 'integer'}, 'type': 'array'}}, 'required': ['shape', 'entries'], 'type': 'object'}}}}, {'if': {'properties': {'type': {'const': 'image'}}}, 'then': {'properties': {'data': {'contentEncoding': 'base64', 'contentMediaType': 'image/png', 'type': 'string'}}}}], 'properties': {'data': {}, 'type': {'enum': ['integer', 'float', 'string', 'duration', 'ndarray', 'image'], 'type': 'string'}}, 'required': ['data', 'type'], 'type': 'object'}}, 'schema': 'http://json-schema.org/draft-07/schema#', 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='results',
            field=models.JSONField(null=True, validators=[dtf.validators.JSONSchemaValidator(schema={'definitions': {'value': {'$id': '#value', 'additionalProperties': False, 'allOf': [{'if': {'properties': {'type': {'const': 'integer'}}}, 'then': {'properties': {'data': {'type': 'integer'}}}}, {'if': {'properties': {'type': {'const': 'float'}}}, 'then': {'properties': {'data': {'type': 'number'}}}}, {'if': {'properties': {'type': {'const': 'string'}}}, 'then': {'properties': {'data': {'type': 'string'}}}}, {'if': {'properties': {'type': {'const': 'duration'}}}, 'then': {'properties': {'data': {'pattern': '^(?P<sign>[-+]?)P(?:(?P<days>\\d+(\\.\\d+)?)D)?(?:T(?:(?P<hours>\\d+(\\.\\d+)?)H)?(?:(?P<minutes>\\d+(\\.\\d+)?)M)?(?:(?P<seconds>\\d+(\\.\\d+)?)S)?)?$', 'type': 'string'}}}}, {'if': {'properties': {'type': {'const': 'ndarray'}}}, 'then': {'properties': {'data': {'additionalProperties': False, 'properties': {'entries': {'items': {'$ref': '#/definitions/value'}, 'type': 'array'}, 'shape': {'items': {'type': 'integer'}, 'type': 'array'}}, 'required': ['shape', 'entries'], 'type': 'object'}}}}, {'if': {'properties': {'type': {'const': 'image'}}}, 'then': {'properties': {'data': {'contentEncoding': 'base64', 'contentMediaType': 'image/png', 'type': 'string'}}}}], 'properties': {'data': {}, 'type': {'enum': ['integer', 'float', 'string', 'duration', 'ndarray', 'image'], 'type': 'string'}}, 'required': ['data', 'type'], 'type': 'object'}}, 'items': {'additionalProperties': False, 'properties': {'name': {'type': 'string'}, 'reference': {'oneOf': [{'$ref': '#/definitions/value'}, {'type': 'null'}]}, 'reference_source': {'type': 'integer'}, 'status': {'default': 'unknown', 'enum': ['skip', 'successful', 'unstable', 'unknown', 'failed', 'broken'], 'type': 'string'}, 'value': {'oneOf': [{'$ref': '#/definitions/value'}, {'type': 'null'}]}}, 'required': ['name', 'value'], 'type': 'object'}, 'schema': 'http://json-schema.org/draft-07/schema#', 'type': 'array'})]),
        ),
    ]
